### ISSUE TITLE
Accordion doesn't render at all on IE11

### ISSUE THREAD

**Issue by DeckOfPandas** [DeckOfPandas/peanut-raspberry#88] opened 2017-10-24 09:27 UTC
From Klynn at BI:

![screen shot 2017-10-24 at 10 27 16](https://user-images.githubusercontent.com/2399432/31935156-f99f1776-b8a5-11e7-980d-f9e32a7b1dcb.png)

**Comment by DeckOfPandas** [comment] 2017-10-24 17:58
Hack fixed in #90 -- removed all animations from sections below the hero

**Comment by DeckOfPandas** [comment] 2017-10-26 07:39
@barneycarroll Ideally we'd have all the sections animated with fadeInUpShort (I can't remember which exactly) or something

**Comment by barneycarroll** [comment] 2017-10-26 11:50
Confirmed fixed on this side. Vote to close.

**Comment by barneycarroll** [comment] 2017-10-26 17:16
Can't reproduce.

**Closed as completed by barneycarroll** 2017-10-26 17:16 UTC
Labels: bug, help wanted, essential
